"""fix unique constraints

Revision ID: 58f246e81cfb
Revises: 3d9e1ed102b6
Create Date: 2025-11-20 14:48:15.331096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f246e81cfb'
down_revision: Union[str, Sequence[str], None] = '3d9e1ed102b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['name'])
    op.create_unique_constraint(None, 'locations', ['name'])
    op.create_unique_constraint(None, 'statuses', ['name'])
    op.create_unique_constraint(None, 'units', ['name'])
    op.create_unique_constraint(None, 'verticals', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verticals', type_='unique')
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_constraint(None, 'statuses', type_='unique')
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
